In [34]:
import numpy as np

# Example 9x9 matrix
matrix = np.array(
    [
        [0, 3, 1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 2, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 2, 0],
        [0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 2, 0, 0, 0, 0, 0],
    ]
)

In [26]:
ones, _ = np.where(matrix == 1)
twos, _ = np.where(matrix == 2)
ones = 9 - ones
# twos = 9 - twos
avg_ones = np.mean(ones)
avg_twos = np.mean(twos)


print(ones)
print(twos)

print(f"Average position of 1s: {avg_ones}")
print(f"Average position of 2s: {avg_twos}")

[8 8 6 3]
[5 3 2 1]
Average position of 1s: 6.25
Average position of 2s: 2.75


In [31]:
ones, _ = np.where(matrix == 3)
9-ones

array([9])

In [35]:
1 in matrix[0, :]

True